# Generated by Django 3.0.5 on 2020-04-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pan_number', models.CharField(max_length=10)),
                ('adhaar_number', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=50)),
                ('income_taxreturn', models.BooleanField()),
            ],
        ),
    ]
