# Generated by Django 3.0.5 on 2020-04-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinfo',
            name='Adhaarupload',
            field=models.FileField(default=0, upload_to=''),
        ),
        migrations.AlterField(
            model_name='clientinfo',
            name='Panupload',
            field=models.FileField(default=0, upload_to=''),
        ),
    ]
