# Generated by Django 3.0.5 on 2020-04-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientinfo',
            name='gst_number',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
