# Generated by Django 3.0.5 on 2020-04-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20200418_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinfo',
            name='Adhaarupload',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='clientinfo',
            name='Panupload',
            field=models.FileField(upload_to=''),
        ),
    ]
